apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    group: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
      tier: backend
  template:
    metadata:
      labels:
        app: node-app
        tier: backend
    spec:
      containers:
        - name: node-app-cont
          image: erickmwarama/kub-first-app:2