apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: backend-app
spec:
  selector:
    app: node-app
    tier: backend
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 8080
      name: app-port
    - protocol: 'TCP'
      port: 443
      targetPort: 443
      name: app-port-ssl
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    group: backend-app
spec:
  replicas: 2
  selector:
    # matchLabels:
    #   app: node-app
    #   tier: backend
    matchExpressions:
      - {key: app, operator: In, values: [node-app, second-app]}
  template:
    metadata:
      labels:
        app: node-app
        tier: backend
    spec:
      containers:
        - name: node-app-cont
          image: erickmwarama/kub-first-app:2