apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: backend-app
spec:
  selector:
    app: node-app
    tier: backend
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 8080
      name: app-port
    - protocol: 'TCP'
      port: 443
      targetPort: 443
      name: app-port-ssl
  type: LoadBalancer